export const UPDATE_PLAYER_STATS = 'UPDATE_PLAYER_STATS';
export const UPDATE_PLAYER_EQUIPMENT = 'UPDATE_PLAYER_EQUIPMENT';
export const UPDATE_PLAYER_QUICKBAR_EQUIPMENT = 'UPDATE_PLAYER_QUICKBAR_EQUIPMENT';