export const SET_CURRENT_PLAYER_HP = 'SET_CURRENT_PLAYER_HP';
export const SET_CURRENT_ENEMY_HP = 'SET_CURRENT_ENEMY_HP';
export const SET_CURRENT_ENEMY_STATS = 'SET_CURRENT_ENEMY_STATS';
export const SET_LOADING = 'SET_LOADING';
export const PLAYER_TAKES_DAMAGE = 'PLAYER_TAKES_DAMAGE';
export const ENEMY_TAKES_DAMAGE = 'ENEMY_TAKES_DAMAGE';