export const SET_MESSAGE = "SET_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const REMOVE_ALL_NOTIFICATIONS = "REMOVE_ALL_NOTIFICATIONS";
export const SET_MODAL = "SET_MODAL";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_INFORMATION_MODAL = "TOGGLE_INFORMATION_MODAL";
