export const UPDATE_PLAYER_STATS = 'UPDATE_PLAYER_STATS';
export const UPDATE_PLAYER_EQUIPMENT = 'UPDATE_PLAYER_EQUIPMENT';
export const UPDATE_PLAYER_QUICKBAR_EQUIPMENT = 'UPDATE_PLAYER_QUICKBAR_EQUIPMENT';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const REDUCE_SINGLE_ITEM = 'REDUCE_SINGLE_ITEM';